### ISSUE TITLE
Use `json.Marshal` convert tuple to array 

### ISSUE THREAD

**Issue by byte-sourcerer** [barweiss/go-tuple#20]
Currently, `tuple.T2[A, B]` is marshaled to `{V1: ..., V2: ...}`. It would be better if it's marshaled to `[..., ...]` just like Rust and Python.

**Comment by barweiss** [comment]
Hi @cjwcommuny! Thank you for reporting this. Indeed I haven't thought to implement JSON marshalling that way.
I'll try to add support to that tomorrow-ish.

**Comment by barweiss** [comment]
Just released v1.1.0 with JSON marshalling and unmarshalling support! Thanks for pointing this missing feature out!
